name: Deploy static to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - '.github/workflows/gh-pages.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - uses: actions/deploy-pages@v4
